// @ts-check

/**
 * @typedef FileType
 * @property { RegExp } pattern
 * @property { (fileContents: string) => Promise<string | null> } minify
 */

const crawl = require("./crawl.cjs");
const { resolve } = require("path");
const { readFileSync, writeFileSync } = require("fs");
const { minify_sync: terser_minify } = require("terser");
const { minify: html_terser_minify } = require("html-minifier-terser");

const BUILD_DIRECTORY = resolve(__dirname, "../build");

const FILES = {
  JS: {
    pattern: /\.js$/,
    minify: minifyJS,
  },
  HTML: {
    pattern: /\.html$/,
    minify: minifyHTML,
  },
  CSS: {
    pattern: /\.css$/,
    minify: minifyCSS,
  },
};

/** @type { import("terser").MinifyOptions } */
const TERSER_OPTIONS = {
  compress: {
    booleans_as_integers: true,
    ecma: 2020,
    expression: true,
    keep_fargs: false,
    passes: 3,
  },
  format: {
    comments: false,
    indent_level: 0,
  },
};
/** @type { import("html-minifier-terser").Options } */
const HTML_TERSER_OPTIONS = {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  includeAutoGeneratedTags: false,
  minifyCSS: true,
  minifyJS: TERSER_OPTIONS,
  minifyURLs: true,
  noNewlinesBeforeTagClose: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
};

minify(BUILD_DIRECTORY);

/**
 * @param { string } buildDirectory
 */
async function minify(buildDirectory) {
  const files = crawl(buildDirectory, "files");
  /** @type { FileType[] } */
  const fileTypes = Object.values(FILES);

  for (const file of files) {
    const fileType = identifyFileType(file, fileTypes);

    if (fileType === null) {
      continue;
    }

    console.log(
      `[minify] | Minifying ${file.slice(buildDirectory.length + 1)}`
    );

    const fileContents = readFileSync(file, "utf-8");
    const minified = await fileType.minify(fileContents);

    if (minified === null) {
      console.warn(`Could not minify file ${file}.`);
      continue;
    }

    writeFileSync(file, minified);
  }

  console.log("[minify] | Finished minifying all files");
}

/**
 * @argument { string } fileContents
 * @returns { Promise<string | null> }
 */
async function minifyJS(fileContents) {
  return terser_minify(fileContents, TERSER_OPTIONS).code ?? null;
}

/**
 * @argument { string } fileContents
 * @returns { Promise<string | null> }
 */
async function minifyHTML(fileContents) {
  return html_terser_minify(fileContents, HTML_TERSER_OPTIONS);
}

/**
 * @argument { string } fileContents
 * @returns { Promise<string | null> }
 */
async function minifyCSS(fileContents) {
  // html-minifier-terser minifies better when it's in a <style> tag
  const newFileContents = `<style>${fileContents}</style>`;
  const minified = await html_terser_minify(
    newFileContents,
    HTML_TERSER_OPTIONS
  );

  return minified.slice(7, minified.length - 8);
}

/**
 * @param { string } file
 * @param { FileType[] } fileTypes
 * @returns { FileType | null }
 */
function identifyFileType(file, fileTypes) {
  const fileType =
    fileTypes.find((fileType) => fileType.pattern.test(file)) ?? null;

  return fileType;
}
